---
name: Linting
description: Runs pre-commit over the repo

inputs:
  ansible-roles-config:
    description: The ansible requirements.yml file
    default: missing

  pre-commit-config:
    description: The pre-commit config file of the current repo
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Cache ansible & pre-commit
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: |-
          ~/.ansible
          ~/.cache/pre-commit
        # yamllint disable-line rule:quoted-strings
        key: "\
          cache-\
          ${{ hashFiles(inputs.ansible-roles-config) }}-\
          ${{ hashFiles(inputs.pre-commit-config) }}\
          "
      if: inputs.ansible-roles-config != 'missing'

    - name: Cache pre-commit
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/.cache/pre-commit
        key: cache-${{ hashFiles(inputs.pre-commit-config) }}
      if: inputs.ansible-roles-config == 'missing'

    - name: Set up uv
      uses: astral-sh/setup-uv@06e4edb239928eb926db9fa84abd11632bf44baa # v7
      with:
        activate-environment: true
        python-version: 3.14

    - name: Install ansible
      shell: bash
      run: uv pip install ansible
      if: inputs.ansible-roles-config != 'missing'

    - name: Install pre-commit
      shell: bash
      run: uv pip install pre-commit

    - name: Install ansible roles
      shell: bash
      run: >-
        uv run ansible-galaxy install -r ${{ inputs.ansible-roles-config }}
        --force
      if: inputs.ansible-roles-config != 'missing'

    - name: Set up terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

    - name: Run pre-commit
      shell: bash
      run: uv run pre-commit run --all-files --color always --verbose

    - uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      if: ${{ !cancelled() }}
