name: Linting
description: Runs pre-commit over the repo

inputs:
  ansible-roles-config:
    description: The ansible requirements.yml file
    default: missing

  pre-commit-config:
    description: The pre-commit config file of the current repo
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - name: Cache pre-commit
      uses: actions/cache@v3
      with:
        path: |-
          ~/.ansible
          ~/.cache/pre-commit
        key: >-
          cache-
          ${{ hashFiles(inputs.ansible-roles-config) }}-
          ${{ hashFiles(inputs.pre-commit-config) }}

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - shell: bash
      run: echo ${{ inputs.ansible-roles-config }}

    - shell: bash
      run: echo ${{ inputs.ansible-roles-config != "missing" }}

    - name: Install ansible
      shell: bash
      run: python -m pip install ansible
      if: ${{ inputs.ansible-roles-config != "missing" }}

    - name: Install pre-commit
      shell: bash
      run: python -m pip install pre-commit

    - name: install ansible roles
      shell: bash
      run: ansible-galaxy install -r ${{ inputs.ansible-roles-config }} --force
      if: ${{ inputs.ansible-roles-config }} != "missing"

    - name: Run pre-commit
      shell: bash
      run: pre-commit run --all-files --color always --verbose
