---
name: Linting
description: Runs prek over the repo

inputs:
  ansible-roles-config:
    description: The ansible requirements.yml file
    default: missing

  pre-commit-config:
    description: The pre-commit config file of the current repo
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Cache ansible & prek
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |-
          ~/.ansible
          ~/.cache/prek
        # yamllint disable-line rule:quoted-strings
        key: "\
          cache-\
          ${{ hashFiles(inputs.ansible-roles-config) }}-\
          ${{ hashFiles(inputs.pre-commit-config) }}\
          "
      if: inputs.ansible-roles-config != 'missing'

    - name: Cache prek
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.cache/prek
        key: cache-${{ hashFiles(inputs.pre-commit-config) }}
      if: inputs.ansible-roles-config == 'missing'

    - name: Set up uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        activate-environment: true
        python-version: 3.14

    - name: Install ansible
      shell: bash
      run: uv pip install ansible
      if: inputs.ansible-roles-config != 'missing'

    - name: Install prek
      shell: bash
      run: uv pip install prek

    - name: Install ansible roles
      shell: bash
      run: >-
        uv run ansible-galaxy install -r ${{ inputs.ansible-roles-config }}
        --force
      if: inputs.ansible-roles-config != 'missing'

    - name: Set up terraform
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

    - name: Run prek
      shell: bash
      run: uv run prek run --all-files --color always --verbose
