# https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/sample-deployment-settings.yml
---
configvalidators:
  - plugin: collaborators
    error: "`Admin cannot be assigned to collaborators`"
    script: >-
      console.log(`baseConfig ${JSON.stringify(baseconfig)}`); return
      baseconfig.permission != 'admin'

overridevalidators:
  - plugin: branches
    error: >-
      `Branch protection required_approving_review_count cannot be overridden to
      a lower value`
    script: >-
      console.log(`baseConfig ${JSON.stringify(baseconfig)}`);
      console.log(`overrideConfig ${JSON.stringify(overrideconfig)}`); if
      (baseconfig.protection.required_pull_request_reviews.required_approving_review_count
      &&
      overrideconfig.protection.required_pull_request_reviews.required_approving_review_count
      ) {
        return
      overrideconfig.protection.required_pull_request_reviews.required_approving_review_count
      >=
      baseconfig.protection.required_pull_request_reviews.required_approving_review_count
      } return true;
  - plugin: labels
    error: Some error
    script: return true

restrictedRepos:
  exclude:
    - -archive$
  include:
