---
name: Project
about: Create a new MIRSG project record
title: "[PROJECT]: <title>"
labels: project
assignees: ""
---

### Brief Summary of Project
<!-- Briefly describe what this project is about. -->
      
```[tasklist]
### Connected ARC Opportunities
- [ ] https://github.com/UCL-ARC/research-software-opportunities/issues/XXX
```  