name: Service Request
description: A service request to the MIRSG team
title: "📥 [REQUEST]: "
labels: ["request"]
body:
  - type: textarea
    id: request-description
    attributes:
      label: Request Description
      description: Describe the request as succinctly as possible
      placeholder: A request to...
    validations:
      required: true
  - type: input
    id: reporter
    attributes:
      label: Request reporter
      description: Who is the request coming from?
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add issues and links related to this request
      value: |
        *
  - type: textarea
    id: request-resolution
    attributes:
      label: Resolution
      description: Describe how the request was completed
      placeholder: This request was completed by...
