---
name: Links
description: Checks the links in a repo work

inputs:
  app-id:
    description: Application ID
    required: true

  app-pem:
    description: Application private key
    required: true

  lychee-args:
    description:
      Arguments to pass to lychee
      (https://github.com/lycheeverse/lychee#commandline-parameters)
    default: --no-progress --verbose .

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
      with:
        app-id: ${{ inputs.app-id }}
        owner: ${{ github.repository_owner }}
        private-key: ${{ inputs.app-pem }}

    - name: Check links
      uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 # v2
      with:
        args: ${{ inputs.lychee-args }}
        failIfEmpty: false
        token: ${{ steps.generate-token.outputs.token }}
