---
name: Links
description: Checks the links in a repo work

inputs:
  app-id:
    description: Application ID
    required: true

  app-pem:
    description: Application private key
    required: true

  lychee-args:
    description:
      Arguments to pass to lychee
      (https://github.com/lycheeverse/lychee#commandline-parameters)
    default: --no-progress --verbose .

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
      with:
        app-id: ${{ inputs.app-id }}
        owner: ${{ github.repository_owner }}
        private-key: ${{ inputs.app-pem }}

    - name: Check links
      uses: lycheeverse/lychee-action@82202e5e9c2f4ef1a55a3d02563e1cb6041e5332 # v2
      with:
        args: ${{ inputs.lychee-args }}
        failIfEmpty: false
        token: ${{ steps.generate-token.outputs.token }}
