name: Add Issues to Project
description: Add issues to the GitHub project board

inputs:
  app-id:
    description: Application ID
    required: true

  app-pem:
    description: Application private key
    required: true

runs:
  using: composite
  steps:
    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-pem }}

    - name: Get project data
      uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/orgs/UCL-MIRSG/projects/3
        github-token: ${{ steps.generate-token.outputs.token }}
