---
name: Add Issues to Project
description: Add issues to the GitHub project board

inputs:
  app-id:
    description: Application ID
    required: true

  app-pem:
    description: Application private key
    required: true

  project-url:
    description: URL of the project board to add issues to
    default: https://github.com/orgs/UCL-MIRSG/projects/3

runs:
  using: composite
  steps:
    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@6c406e8a244fdf6bbf79e6cc8a91504a48d2c2ce # v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-pem }}

    - name: Get project data
      uses: actions/add-to-project@31b3f3ccdc584546fc445612dec3f38ff5edb41c # v0.5.0
      with:
        project-url: ${{ inputs.project-url }}
        github-token: ${{ steps.generate-token.outputs.token }}
