name: Add Issues to Project
description: Add issues to the GitHub project board

runs:
  using: "composite"
  steps:
    - name: Generate token
      id: generate-token
      uses: tibdex/github-app-token@v1.9.0
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PEM }}

    - name: Get project data
      uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/orgs/UCL-MIRSG/projects/3
        github-token: ${{ steps.generate-token.outputs.token }}
