---
name: Molecule Test
description: Run a given molecule command on an Ansible role

inputs:
  scenario:
    description: Name of the scenario to run molecule on
    required: false
    default: default
  base_config:
    description: Path to the base molecule configuration
    required: false
    default: ./.config/molecule/config.yml
  checkout_path:
    description: Path to use when checking out the repository
    required: false
    default: ./
  tests_path:
    description: Change to this directory before running the molecule command
    required: false
    default: ./
  ansible_major_version:
    description: Version of Ansible to use
    default: latest
  molecule_command:
    description: Command to run with molecule
    default: test

runs:
  using: composite
  steps:
    - name: Check out the codebase
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        path: ${{ inputs.checkout_path }}

    - name: Set up uv
      uses: astral-sh/setup-uv@06e4edb239928eb926db9fa84abd11632bf44baa # v7
      with:
        activate-environment: true
        python-version: 3.14

    - name: Install dependencies
      shell: bash
      run: >-
        sudo apt-get update && sudo apt-get -y install rsync; uv pip install
        molecule molecule-plugins[docker] docker requests

    - name: Install Ansible ${{ inputs.ansible_major_version }}
      if: ${{ inputs.ansible_major_version != 'latest' }}
      shell: bash
      run: uv pip install ansible==${{ inputs.ansible_major_version }}.*

    - name: Install Ansible latest version
      if: ${{ inputs.ansible_major_version == 'latest' }}
      shell: bash
      run: uv pip install ansible

    - name: Run molecule command
      shell: bash
      run: >-
        cd "${{ inputs.tests_path }}"; uv run molecule --base-config "${{
        inputs.base_config }}" ${{ inputs.molecule_command }}
        --scenario-name  "${{ inputs.scenario }}"
