name: Add Issue to project
on:
  workflow_call:

jobs:
  add_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: Get project data
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/UCL-MIRSG/projects/3
          github-token: ${{ steps.generate_token.outputs.token }}
