---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: ./actions/links
        with:
          app-id: ${{ vars.LINKS_APP_ID }}
          app-pem: ${{ secrets.LINKS_PRIVATE_KEY }} # zizmor: ignore[secrets-outside-env]
          lychee-args:
            --no-progress --verbose . --exclude
            https://github.com/orgs/UCL-MIRSG/projects/3
