---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      - name: Checkout source
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
          repository: ${{ github.repository }}

      - uses: ./actions/links
        with:
          app-id: ${{ vars.LINKS_APP_ID }}
          app-pem: ${{ secrets.LINKS_PRIVATE_KEY }} # zizmor: ignore[secrets-outside-env]
          lychee-args:
            --no-progress --verbose . --exclude
            https://github.com/orgs/UCL-MIRSG/projects/3
