---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - uses: ./actions/linting
        with:
          pre-commit-config: ./.pre-commit-config.yaml
