name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    name: linting ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Run pre-commit over the repo
        uses: ./actions/linting
        with:
          pre-commit-config: ./.pre-commit-config.yaml
