---
name: Linting

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  linting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Run pre-commit over the repo
        uses: ./actions/linting
        with:
          pre-commit-config: ./.pre-commit-config.yaml
