name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/linting
        with:
          pre-commit-config: ./.pre-commit-config.yaml
