---
name: Manage issues on the projects board

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    permissions: {}
    runs-on: ubuntu-slim
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ./actions/add-to-project
        with:
          app-id: ${{ secrets.APP_ID }} # zizmor: ignore[secrets-outside-env]
          app-pem: ${{ secrets.APP_PEM }} # zizmor: ignore[secrets-outside-env]
