---
name: Manage issues on the projects board

# yamllint disable-line rule:truthy
on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: UCL-MIRSG/.github/actions/add-to-project@f7de6ccf89dd8d7b5417a1ebd14e1618e7c72000 # v0.77.0
        with:
          app-id: ${{ secrets.APP_ID }}
          app-pem: ${{ secrets.APP_PEM }}
