---
name: Manage issues on the projects board

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    permissions: {}
    runs-on: ubuntu-slim
    steps:
      - name: Checkout source
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
          repository: ${{ github.repository }}

      - uses: ./actions/add-to-project
        with:
          app-id: ${{ secrets.APP_ID }} # zizmor: ignore[secrets-outside-env]
          app-pem: ${{ secrets.APP_PEM }} # zizmor: ignore[secrets-outside-env]
